const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CLEAR_CART = 'CLEAR_CART';
const SHOW_ALERT = 'SHOW_ALERT';
const HIDE_ALERT = 'HIDE_ALERT';

export {
	ADD_TO_CART,
	REMOVE_FROM_CART,
	CLEAR_CART,
	SHOW_ALERT,
	HIDE_ALERT
}

